package ru.rentoptima.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.rentoptima.entity.Booking;
import ru.rentoptima.entity.Expense;
import ru.rentoptima.entity.ExpenseCategory;
import ru.rentoptima.repository.ExpenseCategoryRepository;
import ru.rentoptima.repository.ExpenseRepository;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Service
@RequiredArgsConstructor
public class ExpenseService {

    private final ExpenseRepository expenseRepo;
    private final ExpenseCategoryRepository categoryRepo;
    private final SettingsService settings;

    public List<Expense> getExpenses(Long tenantId, LocalDate from, LocalDate to) {
        return expenseRepo.findByTenantIdAndDateBetweenOrderByDateDesc(tenantId, from, to);
    }

    public List<Expense> getRecentExpenses(Long tenantId, int limit) {
        return expenseRepo.findTopByTenantIdOrderByDateDesc(tenantId, limit);
    }

    public List<ExpenseCategory> getCategories(Long tenantId) {
        return categoryRepo.findByTenantIdOrderBySortOrder(tenantId);
    }

    @Transactional
    public Expense createExpense(Long tenantId, Long propertyId, Long categoryId,
                                  BigDecimal amount, LocalDate date, String comment) {
        Expense expense = new Expense();
        expense.setTenantId(tenantId);
        expense.setPropertyId(propertyId);
        expense.setCategoryId(categoryId);
        expense.setAmount(amount);
        expense.setDate(date);
        expense.setComment(comment);
        expense.setAutoGenerated(false);
        return expenseRepo.save(expense);
    }

    @Transactional
    public void createCleaningExpense(Booking booking) {
        Long tenantId = booking.getTenant().getId();
        int cleaningCost = settings.getIntValue(tenantId, "cleaning_cost", 1400);

        // Find "Уборка" category
        ExpenseCategory cleaningCategory = categoryRepo
                .findByTenantIdAndName(tenantId, "Уборка")
                .orElse(null);
        if (cleaningCategory == null) return;

        // Check if already created for this booking
        if (expenseRepo.existsByBookingId(booking.getId())) return;

        Expense expense = new Expense();
        expense.setTenantId(tenantId);
        expense.setPropertyId(booking.getProperty().getId());
        expense.setCategoryId(cleaningCategory.getId());
        expense.setAmount(BigDecimal.valueOf(cleaningCost));
        expense.setDate(booking.getCheckOut());
        expense.setComment("Уборка после выезда: " + (booking.getGuestName() != null ? booking.getGuestName() : "гость"));
        expense.setAutoGenerated(true);
        expense.setBookingId(booking.getId());
        expenseRepo.save(expense);
    }

    public BigDecimal getTotalExpenses(Long tenantId, LocalDate from, LocalDate to) {
        BigDecimal total = expenseRepo.sumByTenantIdAndDateBetween(tenantId, from, to);
        return total != null ? total : BigDecimal.ZERO;
    }
}
